name: Create artifacts

on:
  workflow_dispatch: {}

jobs:
  create:
    runs-on: ubuntu-latest
    steps:
      - run: |
          mkdir v1.0.0
          touch v1.0.0/example.txt
          touch v1.0.0/example2.txt
      - run: |
          mkdir v1.0.1
          touch v1.0.1/example.txt
          touch v1.0.1/example2.txt
      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
        with:
          name: artifacts-v1.0.0
          path: v1.0.0
          retention-days: 1
      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
        with:
          name: artifacts-v1.0.1
          path: v1.0.1
          retention-days: 1
  use:
    uses: kminehart/patch-testing/.github/workflows/use-artifacts.yml@main
    with:
      run-id: ${{ github.run_id }}
    needs:
      - create

