name: Sync pull requests to the patches repository

on:
  pull_request:
    types: [opened, reopened, synchronized]
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  create-patch-and-open-pr:
    if: github.repository == 'kminehart/patch-testing-mirror'
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3
      - name: Checkout active patches
        uses: actions/checkout@v3
        with:
          repository: kminehart/patches
          path: patches
      - name: Create patch
        run: |
          git format-patch ${{github.event.pull_request.head.ref}}..${{github.event.pull_request.head.ref}} --stdout > diff.patch
          cat diff.patch
