name: Use artifacts

on:
  workflow_call:
    inputs:
      pattern:
        type: string
        required: false
      artifact:
        type: string
        required: false
      run-id:
        type: string
        required: false
        default: ${{ github.run_id }}

jobs:
  use:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093
        with:
          pattern: ${{ inputs.pattern }}
          run-id: ${{ inputs.run-id }}
          path: ./artifact
      - run: ls -al artifact
